<a href="https://colab.research.google.com/github/Turzzz/MI-Basic/blob/main/01.Basic%20Reshape.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import tensorflow as tf

print(tf.version)
# t=tf.zeros([2,2,3,2,5]);
t=tf.zeros([3,4]);
t=tf.reshape(t,[4,-1]);
print(t);


<module 'tensorflow._api.v2.version' from '/usr/local/lib/python3.6/dist-packages/tensorflow/_api/v2/version/__init__.py'>
tf.Tensor(
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]], shape=(4, 3), dtype=float32)
